# Generated by Django 5.0.5 on 2024-05-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptapp', '0003_alter_recipebook_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('fi', 'первое блюдо'), ('se', 'второе блюдо'), ('ice', 'холодное блюдо'), ('sw', 'сладкое блюдо'), ('sn', 'закуски')], max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('me', 'мясное'), ('te', 'мучное'), ('fi', 'море продукты'), ('ic', 'мороженое'), ('ve', 'овощное'), ('fr', 'фруктовое')], max_length=100),
        ),
    ]
