# Generated by Django 5.0.5 on 2024-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptapp', '0004_alter_category_title_alter_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
