# Generated by Django 5.0.5 on 2024-05-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptapp', '0006_remove_recipebook_rating_alter_recipebook_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title_category',
        ),
    ]
